### ISSUE TITLE
[Performance] byte[] Allocations JImGuiUtil.class

### ISSUE THREAD

**Issue by Mr00Anderson** [ice1000/jimgui#29]
I want to throw this out for ideas. I noticed large memory usage and garbage collection spikes and tracked it down to the [JImGuiUtil.class](https://github.com/ice1000/jimgui/blob/ccdd8660131fb4fcb3e896745d748d9474c2a8cf/core/src/org/ice1000/jimgui/util/JImGuiUtil.java#L117). I started working on changes but realized the code generation. 

The change I was going to make and propose is putting a `Function<String, byte[]>` in `JImGui.class` to allow overriding of how strings are turned into bytes. This will allow a much easier way to mass override this behavior. 

I made changes locally and overrode JImGui and was able to cut down 1 million allocations on byte arrays with a short test and about 4900 ms down to about 1270 ms. This is a big gain and I only did a partial test. I did not replace all the `JImGuiUtil#getBytes` in the API, so it would be more impact on a default scale; then my minor change locally. 

```java
public class JaweJImGui extends JImGui {
    public void text(@NotNull byte[] text) {
        textUnformatted(text);
    }
}
```

```java
    public static final WeakHashMap<String, byte[]> cachedBytes = new WeakHashMap<>();

    public static void text(JaweJImGui imGui, JaweText drawable0){
        byte[] bytes = cachedBytes.computeIfAbsent(drawable0.text, s -> s.getBytes(StandardCharsets.UTF_8));
        imGui.text(bytes);
    }
```
Before Changes:
![Screenshot_5](https://user-images.githubusercontent.com/1356935/58753560-de38d600-848e-11e9-9a71-dfd44a148af7.png)
![Screenshot_3](https://user-images.githubusercontent.com/1356935/58753561-de38d600-848e-11e9-9f23-d442c3df7f51.png)
![Screenshot_4](https://user-images.githubusercontent.com/1356935/58753562-de38d600-848e-11e9-9724-310d5b06b2be.png)

After Changes:
![Screenshot_8](https://user-images.githubusercontent.com/1356935/58754004-4212cd00-8496-11e9-965f-ef30ca7a3a0e.png)
![Screenshot_6](https://user-images.githubusercontent.com/1356935/58754005-4212cd00-8496-11e9-9242-47425646a5b4.png)
![Screenshot_7](https://user-images.githubusercontent.com/1356935/58754006-4212cd00-8496-11e9-932c-d109d0e1f496.png)

**Comment by ice1000** [comment]
Added support for customizing the conversion function. Open new issue if it's not what you want.

**Comment by ice1000** [comment]
Btw, this kind of feedback is exactly what I wanted. If you have more issues to spot, no matter how small they are, please file an issue and have a discussion with me.

**Comment by ice1000** [comment]
I think I've just come up with a better solution -- do only one `getBytes` call and always use that `byte[]` afterward. I'll still provide interface for `String` because I don't way to break API

**Comment by Mr00Anderson** [comment]
> Btw, this kind of feedback is exactly what I wanted. If you have more issues to spot, no matter how small they are, please file an issue and have a discussion with me.

Sweet. I definitely will open up any issues or items for discussion. I will share my library soon. Its on github, just not ready enough to be a listed at the moment. Its a detached editor. Can be used without libgdx, or eventually with. The entity system will be inter changeable but by default is using artemis obd. Basically working it so the editor by default is used to write the real game editor, or used to make simple games. Originally it was just for me to use for school projects and world generation testing. Now I want it to be shared by anyone who wants.

> I think I've just come up with a better solution -- do only one `getBytes` call and always use that `byte[]` afterward. I'll still provide interface for `String` because I don't way to break API

I will be more value in making better contributions once I learn your libraries build process. Besides school my full time job is this game editor.

**Comment by ice1000** [comment]
> I will be more value in making better contributions once I learn your libraries build process. Besides school my full time job is this game editor.

I can explain it to you. I'll put it into another comment

**Comment by ice1000** [comment]
As you can see I'm using Gradle to handle all of this, but CMake and a native C++ build system is also required. This is all because mixing Java and C++ in one project is hard.

This comment assumes knowledge on Java, Gradle, JNI, basic C++, CMake.

I am the kind of people who will never commit generated files into a git repo, so does the files can be downloaded as dependencies, like the imgui basic libraries.

The Gradle script:

0. First, download the imgui core library, the stb image decoding library (because I want to handle image rendering for jimgui users because imgui doesn't) and imgui's default wrappers for dx9, win32, glfw and opengl3. I use dx9+win32 for Windows and GLFW/OGL3 for *nix. Yes, it's just downloading files from GitHub.
0. Generate the JNI interface, their corresponding C++ implementations, and some wrappers that deal with default parameters. I'm using some Kotlin scripts to do the generation -- it's just some string manipulation. I'd use Perl if I have learned Perl when I created this project, but at that time I didn't know Perl. The scripts are under `buildSrc`.
0. Compile the Java codes, with JNI header files generated.
0. Invoke `cmake` in command-line to generate a C++ project, including the downloaded imgui core libraries and default wrapper, generated C++ implementations, hand-written bindings (that the generator is not smart enough to handle), and the header files generated by Java compilation.
0. Invoke `msbuild` on Windows and `make` on *nix to build the project generated by cmake, both are invoked as command-line programs.
0. Copy the compiled C++ libraries to `core/res/native`, which is the resource directory.

Now you get a jar file that only works on your platform.
For me, the owner who need to publish jimgui as a library, I need to ask someone who owns a mac to compile the dylib for me because I'm poor. I have a Windows machine and a Linux machine, which means I can at least build native libraries for these two platforms. I need all of the resource files, put them into `core/res/native`, and then publish it to bintray.

That's all.

**Comment by ice1000** [comment]
Well, besides school I am a type theory guy.
